image: Visual Studio 2015

environment:
    global:
        BOOST_ROOT: c:\Libraries\boost
        BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

build_script:
    - dir C:\Libraries\boost_1_65_1\libs
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    - mkdir build
    - cd build
    - cmake -G"MinGW Makefiles" .. -DSSL_SUPPORT_MBEDTLS=OFF
    - cmake --build .
