image: Visual Studio 2015

environment:
    global:
        MINGW_ROOT: C:\msys64\mingw64
        BOOST_ROOT: C:\msys64\mingw64
        BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
        BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
        CMAKE_GENERATOR: 'MSYS Makefiles'
        
install:
    - cmd: set PATH=%BOOST_LIBRARYDIR%;%PATH%
    - cmd: set PATH=%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%
    - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-boost"

build_script:
    - cmake -E make_directory build
    - cd build
    - cmake -G"MinGW Makefiles" .. -DSSL_SUPPORT_MBEDTLS=OFF
    - cmake --build .
