image: Visual Studio 2015

environment:
    global:
        BOOST_ROOT: C:\Libraries\boost_1_60_0
        
install:
    - cmd: rename "C:\Program Files\Git\usr\bin\sh.exe" "sh-ignored.exe"
    - cmd: set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\;%PATH%

build_script:
    - cmake -G"MinGW Makefiles" . -DSSL_SUPPORT_MBEDTLS=OFF
    - cmake --build .
