image: Visual Studio 2015

build_script:
    - dir C:\Libraries\boost_1_65_1\
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    - mkdir build
    - cd build
    - cmake -G"MinGW Makefiles" .. -DBOOST_ROOT=C:\Libraries\boost_1_65_1 -DSSL_SUPPORT_MBEDTLS=OFF
    - cmake --build .
